### ISSUE TITLE
ODF Variables Type/Code Detection and matching to existing vocabulary GF3/BODC/CF

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-siooc_data_transform#24]
An important aspect of the conversion of the ODF files is to make sure the appropriate metadata and attributes are carried over within the NetCDF and potentially improved. 

It would be important to develop an algorithm that can suggest BODC/CF vocab attributes to some of the potential variables based few already existing attributes within the ODF file (name, units, code)

The following files or potentially more updated ones could be a good start :
[bio_gf3_p01_mapping_2.7.2.xlsx](https://drive.google.com/file/d/1PINIFfkgGOjkcvGRgjip9Wa3vqcqdets/view?usp=sharing)
[meds_code_20191212.csv](https://drive.google.com/file/d/1OOi8SQX2_RLwUpPnPF5VurafuLLxj4H-/view?usp=sharing)

**Comment by pramod-thupaki** [comment]
This file with DFO MEDS pcodes will also be useful for addressing this issue:
https://drive.google.com/file/d/1UAGMop-dQeVXiU-rgsOGLfFgJm4jAgkW/view?usp=sharing

**Comment by guillotp** [comment]
I can update the dictionary with Québec-Océan vocabulary which is very similar with MLI codes.

**Comment by JessyBarrette** [comment]
@guillotp @jeffcullis
You can find [here ](https://github.com/cioos-siooc/cioos-siooc_data_transform/blob/odf_transform/odf_transform/vocabulary/dfo_vocabulary_list.csv) a csv file that list a lot of GF3 codes which is essentially a merge of the list provided by BIO and MEDS.

For all the BIO variables that MEDS said MLI had the same code and same unit, I merged the BODC P01 vocabulary, and also used the MEDS and BIO CF name for each of them if available. That could be a good start for adding more documetation regarding different variables.

**Comment by JessyBarrette** [comment]
Github doesn't show the extra columns but there's CF(P07) and BODC (P01) names in there.

**Comment by JessyBarrette** [comment]
There's a notebook in the repo now that show how the merge was done and how the json and csv files where generated.
You can quickly look at how it's been done here:
https://colab.research.google.com/github/cioos-siooc/cioos-siooc_data_transform/blob/odf_transform/odf_transform/vocabulary/ReviewDFO_Variables.ipynb

**Comment by JessyBarrette** [comment]
SeaDataNet recommend defining their vocabullary by using the following convention (example from [here](https://www.seadatanet.org/Standards/Data-Transport-Formats)):
```
		TEMP:sdn_parameter_urn = "SDN:P01::TEMPPR01" ;
		TEMP:sdn_parameter_name = "Temperature of the water body" ;
		TEMP:sdn_uom_urn = "SDN:P06::UPAA" ;
		TEMP:sdn_uom_name = "Degrees Celsius" ;
```
We will modify the vocab json output to be comparable to this

**Comment by JessyBarrette** [comment]
I will close this issue and split it in different tasks to simplify the next steps
