### ISSUE TITLE
Generate french language compatible meta attributes and text

### ISSUE THREAD

**Issue by pramod-thupaki** [cioos-siooc/cioos-siooc_data_transform#25]
Modify code to add french language compatible meta attributes and text. Add new attribute such as "<>_f" ? What are the standards ?

Some text are also not correctly encoded using UTF-8; this bug affects all text in ODF files, including header, variable names and summary.

**Comment by sjbruce** [comment]
I had noticed from a couple of sample files I worked with a few weeks ago that the encoding was CP1252, I believe the sample file was from QO. The OCE package - at least through rpy2 was expecting UTF-8 explicitly.

Perhaps a pre-processing step would be to check the source file encoding and if not UTF-8 convert it and then carry on.
