### ISSUE TITLE
MLI ODF Flag interpretation by the OCE package

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-siooc_data_transform#28]
The OCE package seems to be acting differently between MLI flag data (at least the one tested [here](https://github.com/cioos-siooc/cioos-siooc_data_transform/blob/odi_data/cioos_data_transform/mli_data/sample_data/2020-12-23/ODF_files_MLI/CTD_2019004_1_2A_DN.ODF)) and other sources. 

Once an MLI file is read by OCE the following flags are provided with just a few letters only:
![image](https://user-images.githubusercontent.com/30420025/107792097-9660ed80-6d09-11eb-88ec-0c284a0fae15.png)

On the other hand other sources are have their flag name attached to the associated variable ([here ](https://drive.google.com/file/d/1KmRsBuflxyX9OQ5HiyJtmmgioFARADgT/view?usp=sharing)'s a file example I believe give that output):
![Screen Shot 2021-02-05 at 10 59 53 AM](https://user-images.githubusercontent.com/30420025/107792308-d4f6a800-6d09-11eb-99a8-a9e8dd0dbbd1.png)

Perhaps this is the expected behavior by MLI. We would need to confirm that, if not either we find a mapping of those MLI flag names to the their corresponding variables or raise an issue within the OCE package (preferred).

**Comment by guillotp** [comment]
BIO flags are different compared to MLI and QO.

Here is a example for QO and MLI
PARAMETER_HEADER,
  TYPE= 'DOUB',
  NAME= 'Sea Pressure (sea surface - 0)',
  UNITS= 'decibars',
  CODE= 'PRES_01',
...
The next parameter could be or not a flag.
PARAMETER_HEADER,
  TYPE= 'DOUB',
  NAME= 'Quality flag: Sea Pressure (sea surface - 0)',
  UNITS= 'none',
  CODE= 'QQQQ_01',

Here is a example for BIO (I think every parameter comes with a flag, no choice).
PARAMETER_HEADER,
  TYPE='DOUB',
  NAME='PRES_01',
  UNITS='db',
  CODE='PRES_01',
...
and the flag
PARAMETER_HEADER,
  TYPE='SING',
  NAME='Quality Flag for Parameter: PRES_01',
  UNITS='none',
  CODE='QPRES_01',

See the difference for the CODE.
I guess BIO format is more recent and probably better that it would induce less errors and confusions.

**Comment by jeffcullis** [comment]
This relates to Pauline's work in #21

**Comment by JessyBarrette** [comment]
An issue regarding this was created on the OCE own repository: https://github.com/dankelley/oce/issues/1808

**Comment by JessyBarrette** [comment]
Since the issue is now handled by the OCE package, I will close the present issue!
