### ISSUE TITLE
NetCDF dimension

### ISSUE THREAD

**Issue by guillotp** [cioos-siooc/cioos-siooc_data_transform#31]
So far, from the test file, z is the unique dimension for the NetCDF filles. Is it a choice ? Could we think to add time, lat and long ?

**Comment by pramod-thupaki** [comment]
'z' is the unique dimension as the example files are CTD profiles. Other file types will have different unique dimensions based on data type (e.g. 'time' for moorings, 'time' and 'z' for ADCPs, and 'time', 'z','lat','lon' for gliders)
