### ISSUE TITLE
Integrate CCADI Terms within the GF3 Dictionary

### ISSUE THREAD

**Issue by JessyBarrette** [cioos-siooc/cioos-siooc_data_transform#67]
CCADI has been working on defining matching vocabularies between GF3 and other vocabularies (CF and BODC) 

It would be good to integrate this effort within the cioos-data-transform tool

**Comment by guillotp** [comment]
Yes, my colleague of Amundsen Science and I are working on a dictionary ton convert btl variables in GF3 (or extended GF3) and GF3 to BODC. It is a hand job (not algorithm to try to detect the best combination), I will check with Jessy how to include it.

**Comment by JessyBarrette** [comment]
Terms were added to the Vocabulary CSV as part of  PR #86

**Comment by JessyBarrette** [comment]
Those terms were added to vocabulary but also moved to the CIOOS seabird package
