### ISSUE TITLE
ObsFile fails to parse mmol/m**3 properly

### ISSUE THREAD

**Issue by cyborgsphinx** [cioos-siooc/cioos-siooc_data_transform#95]
I've come across some shell files that list oxygen concentration in mmol/m**3, and the **3 part of that is being cut off so the unit shows up as mmol/m.

**Comment by pramod-thupaki** [comment]
Can you add links to some example files ? That would help us find and fix the bug.

**Comment by cyborgsphinx** [comment]
Sorry, I should have included that originally. Here's an example file:
https://www.waterproperties.ca/osd_data_archive/Cruise_Data/MEDS_Files/NCOASTX/0090/00900087.BOT

**Comment by pramod-thupaki** [comment]
Oxygen concentration should not be in mmol/m3;  units compatible with BODC codes used in this repo can be seen here:
https://github.com/cioos-siooc/cioos-siooc_data_transform/blob/de0134d0d2cb3f62a97c5a15605607d63175fc38/cioos_data_transform/cioos_data_transform/OceanNcVar.py#L642

Please convert to one of the compatible units and try running the python code again. 

Also, the file linked is part of 'MEDS files' and as such not included in the CIOOS archive.
